---

replicaCount: 1

# slapd configuration section. Some special variables can be used:
#
#   - @UID@: replaced with the process uid
#   - @GID@: replaced with the process gid
#   - @REPLICATOR@: replaced with the replicator DN
#   - @REPLICATOR CREDENTIALS@: replaced with the replicator password
#   - @MANAGER@: replaced with the manager DN
#   - @SUFFIX@: replaced with the LDAP tree suffix (dc=...,dc=...)
#
config:
  extraModules: []
  extraSchemas: []
  configDatabaseExtraAccess: []
  monitorDatabaseExtraAccess: []

  consumer:
    accesslogDatabaseMaxSize: "1073741824"
    accesslogDatabaseExtraAccess: []

    mdbDatabaseMaxSize: "1073741824"
    mdbDatabaseExtraAccess: []

  provider:
    accesslogDatabaseMaxSize: "1073741824"
    accesslogDatabaseExtraAccess: []

    mdbDatabaseMaxSize: "1073741824"
    mdbDatabaseExtraAccess: []

# Used for the provider connection over LDAPS
clusterDomain: "cluster.local"

persistence:
  enabled: False
  # storageClassName: ""
  # size: 128Mi

image:
  repository: ghcr.io/mikavl/openldap-helm-chart
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000

service:
  type: ClusterIP
  port: 636

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
